# yaml-language-server: $schema=./node_modules/somod-schema/schemas/parameters/index.json

parameters:
  chat.http-api.id:
    type: string
  chat.websocket-api.id:
    type: string
  chat.enable.websocket:
    type: boolean
    default: true
  dynamodb.pitr.enable:
    type: boolean
    default: false
  authorizer.jwt.secret:
    type: string
